/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package PooDio;

public class App {

    public static void main(String[] args) {
        Cliente rafael = new Cliente();
        rafael.setNome("Rafael "); 
        Conta cc = new ContaCorrente(rafael);
        Conta poupanca = new ContaCorrente(rafael);
        cc.depositar(3000000);
        poupanca.depositar(3333333);
        cc.imprimirExtrato();
        poupanca.imprimirExtrato();
        cc.transferir(3000000, poupanca);
        System.out.println("Obrigado Deus Por me ajudar a ser programador");
        
        
    }
}
